### ISSUE TITLE
Thank you for the shoutout in the description

### ISSUE THREAD

**Issue by GeoSn0w** [iBootBeta2/OXUL103-Jailbreak#23]
I don't understand why you want beef but won't fall for it.

You call me over for calling you out... 
Let me share with you a lesson that I've learned the hard way, maybe will stop you from faking Jailbreaks and will drive you to learn to actually code shit: I am a beginner myself, I've started from very low ground (ground 0 is still high compared to where I've started). When I started to get involved more intensely in iOS Exploiting and when I've decided 6 months ago that I want to actually learn better to do better and to become a better developer, I did not know much of a thing about iOS.

Was it a long journey up until this point? Yes. But now I know better. Now I have a an idea or two about what SEP does, and how SEP interacts with iOS, about the AP (Application Processor) and what it does / how it sets the TrustZone(s) and how it shares some memory with SEP (protected of course). I've got an idea or two on how iOS applications work - in terms of SandBoxing, AMFI, who enforces CodeSign on iOS and why, how are the Entitlements working and how are they checked. I've got an idea or two about KPP / AMCC / memprot, why we can't simply patch them and why we have to bypass them, but more important, what these components do and why they're a wall of protection when it comes to Jailbreak. I have an idea or two about types of exploits commonly used, I am pretty sure I haven't studied them all, but having an idea about TOCTOU, Use after free, Buffer / Stack / Heap Overflow, String format exploits and so on, helps me have a 500 times better picture of iOS than I had half a year ago. 

Conclusion?
I've been an absolute beginner like you. I've made (bad) mistakes like you, I've beefed with other devs, like you, but that did not stop me to learn better and to start a process of in-depth study so that I can prove the devs with which I've ever beefed, that I can code for the community. Why don't you try that as well?

Your Jailbreak isn't even a Jailbreak, and you know that. If it was that simple....
Combining yalu for iOS 8.4.1 (incomplete) + mach_portal by Ian beer of Google Project 0 + yalu102 by Luca Todesco + extra_recipe by @xerub + some random files that make no sense in which you "credit" me (GeoSn0w) for the kernel exploit don't add up for a Jailbreak. It is not as simple as combining older Jailbreak files....

Can you reuse exploits from previous Jailbreaks?
Of course, sometimes an exploit from a previous Jailbreak can be used at least as an idea of where to attack. There might be similar vulnerabilities on the newer iOS versions as well, but that doesn't mean you can copy that exploit and just use it unless it is a 0day about which Apple has no idea and it therefore persists on newer versions (but then you wouldn't find it on older Jailbreak, would you?).

To sum up, yet again, you can hate me for calling you over for your fake Jailbreak, but I've done that solely because: 

1. You've implied I have anything to do with it by stuffing my dev name (GeoSn0w) randomly in your project.
2. I wanted to (at least try) to show you the way as I have been shown some time ago...

I know you will close the ticket as you do with all of them, don't forget, closing it won't remove it from closed tickets. 
Take these pieces of advices as my beginnery opinion. I am a beginner myself and I can tell you - you feel 300 times better when someone calls you out for how good your application you've just made is, rather than when someone calls you out because you don't make sense / have to learn more / you're spreading misinformation (purposefully or not). I've learned these lessons the hard way, if you want to use them for your own personal progress, do it, if you don't, don't, but if you don't stop trashtalking me on Github for calling your fake Jailbreak out, I might as well report the project to GitHub. This is a place for code, not for beef. 

I wish you success in life.

**Comment by iBootBeta2** [comment]
Thanks, you too. Bye.

**Comment by iBootBeta2** [comment]
-update-
Okay, okay.
I've read over this, yes I'm a dumbass crediting you like a lunatic, but. That Jailbreak part did belong to you, yes! I did add other sources, and yes I'm still learning. Re-reading this changes my mind, I'm an idiot doubting you. I'm sorry, I'll no longer update on this repository. I'll remove all "Jailbreak Particles" implying an exploit & jailbreak for 10.3x.

How will I resolve this?
- By never copying sources, implying false information, understanding "credit" doesn't mean just writing who made it. And I'll fix this by resolving this issue and giving the Correct Information.
- I'll get lessons for coding, I'm a nub at C+ coding, I'll fix this. Trust me, this will not become an issue again for either me nor you.
- If I want to attempt something, I'll make "the" or "a" repository Private.

Why did I start this?
- Because I thought I could do the impossible, obviously I could not.
- I believed i had something, I obviously did not.
- I hoped I would succeed, obviously did not.
- I thought this would be a little test for me and my friends to work on if we had time, I've worked on this in school, I.T (particularly).

What I think?
- I appreciate a ton for your response, yes! I've been a dick, but that's the way I meet new people. I didn't expect this to turn the tables on me, I've returned my gratitude in respect and care.
- I will respect you like you did to me. I love the support & tips, especially from an expert like you!
- I hope to see you succeeding with your life & your YouTube life, Thanks!

I appreciate this, thanks!!

**Comment by jailbreaklover** [comment]
@iBootBeta2 now that how it's business came to make friends, wonderful and I hope that @GeoSn0w forgive you! Keep working iBoot we are excited for you JB!

**Comment by iBootBeta2** [comment]
@jailbreaklover  @GeoSn0w  thanks!

**Comment by iBootBeta2** [comment]
I'll leave this issue ticket open.

**Comment by madoksystem** [comment]
Hello,seems you're bout to get the jailbreak out ? Or not yet ?

**Comment by iBootBeta2** [comment]
Yes @madoksystem waiting for the queue!

**Comment by madoksystem** [comment]
Oh ok :) honestly don't really understand what is that means but i guess that the jailbreak wouldn't be ready today 🤔

**Comment by iBootBeta2** [comment]
I'll have to wait for another iOS beta release, so I can confirm.

**Comment by madoksystem** [comment]
Confirm what?

Envoyé de mon iPhone

**Comment by jailbreaklover** [comment]
@iBootBeta2 iOS 10.3.3 was released!!

**Comment by iBootBeta2** [comment]
Great! Now we wait for the ipa, wait a couple of days. confirmed release will be soon.

**Comment by ljk4160** [comment]
come on!

**Comment by iBootBeta2** [comment]
@ljk4160  I'm trying my best here, man!

**Comment by jailbreaklover** [comment]
Patience, this just the beginning guys, let iBoot complete the ipa.

**Comment by iBootBeta2** [comment]
@jailbreaklover  thank you!

**Comment by Ankiiii** [comment]
Hopefully, I can get my iPhone fixed before the ipa is done.

**Comment by jailbreaklover** [comment]
Is necessary the device that will make the test of the JB can't have password and the find my phone off?

**Comment by iBootBeta2** [comment]
@Ankiiii  fingers crossed for you! @jailbreaklover  you need passcode off and find my phone
